package com.varwof.aic.jwt;

import com.varwof.aic.AicException;
import org.junit.jupiter.api.Test;

import java.net.InetAddress;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * End-to-end validation pipeline tests plus cross-language verification of
 * tokens generated by the Go reference implementation.
 */
class JwtValidatorTest {

    private static final long IAT = 1755500000L;
    private static final String AGENT_ID = "agent:db-analyst-01";
    private static final String REALM = "corp.com";
    private static final String PRINCIPAL_ID = "zhangsan";
    private static final String ISSUER = "https://ca.example.com/aic";
    private static final String AUDIENCE = "https://gw.example.com";

    /** Builds a complete authorized-mode token pair signed in Java. */
    private static final class Pair {
        KeyPair principal;
        KeyPair issuer;
        String keyHash;
        String jkt;
        String nonce;
        String daToken;
        String outerToken;
    }

    private static Pair build() throws Exception {
        Pair p = new Pair();
        p.principal = ec();
        p.issuer = ec();
        p.keyHash = KeyHash.spkiHashPub(p.principal.getPublic(), "sha-256");
        p.jkt = KeyHash.keyHashOf(p.principal.getPublic(), "jkt");
        byte[] n = new byte[32];
        new SecureRandom().nextBytes(n);
        p.nonce = Jws.b64uEncode(n);

        Claims.Header daHdr = new Claims.Header("ES256", Validator.TYP_DA, "principal-1");
        Claims.DaClaims da = new Claims.DaClaims();
        da.ver = 1;
        da.agentId = AGENT_ID;
        da.principal = new Claims.Principal(REALM, PRINCIPAL_ID, p.keyHash, "sha-256");
        da.reason = new Claims.Reason("DATA_ANALYSIS", "Scheduled production data analysis window");
        da.capabilities = new ArrayList<>();
        da.capabilities.add(capDatabase(100));
        da.delegationMode = Validator.MODE_AUTHORIZED;
        da.requestedLifetime = 3600;
        da.ts = IAT;
        da.nonce = p.nonce;
        List<Claims.Capability> constraints = new ArrayList<>();
        constraints.add(new Claims.Capability("varwof/constraint-v1", "allowed-cidr",
                JwtJson.parse("[\"10.0.0.0/8\"]")));
        da.constraints = constraints;
        byte[] daPayload = serialize(da);
        p.daToken = Jws.signCompact(serialize(daHdr), daPayload, "ES256", p.principal.getPrivate());

        Claims.Header outerHdr = new Claims.Header("ES256", Validator.TYP_OUTER, "ca-2026-01");
        Claims.OuterClaims outer = new Claims.OuterClaims();
        outer.iss = ISSUER;
        outer.sub = AGENT_ID;
        outer.aud = new Claims.Audience(List.of(AUDIENCE));
        outer.iat = IAT;
        outer.exp = IAT + 3600;
        outer.jti = p.nonce;
        outer.cnf = new Claims.Cnf(p.jkt);
        outer.aic = new Claims.AicClaims(1,
                new Claims.Principal(REALM, PRINCIPAL_ID, p.keyHash, "sha-256"),
                Validator.MODE_AUTHORIZED, new ArrayList<>(da.capabilities));
        outer.aic.chainDepth = 0;
        outer.aic.maxDepth = 1;
        outer.aic.constraints = constraints;
        outer.da = p.daToken;
        byte[] outerPayload = serialize(outer);
        p.outerToken = Jws.signCompact(serialize(outerHdr), outerPayload, "ES256", p.issuer.getPrivate());
        return p;
    }

    private static Claims.Capability capDatabase(long maxRows) {
        return new Claims.Capability("database", "query:SELECT", JwtJson.parse("{\"max_rows\":" + maxRows + "}"));
    }

    private static byte[] serialize(Object o) {
        try {
            return JwtJson.MAPPER.writeValueAsBytes(o);
        } catch (Exception ex) {
            throw new RuntimeException(ex);
        }
    }

    private static KeyPair ec() throws Exception {
        KeyPairGenerator g = KeyPairGenerator.getInstance("EC");
        g.initialize(256);
        return g.generateKeyPair();
    }

    private static Validator.VerifyOptions fullOpts(Pair p, long now) throws Exception {
        Validator.VerifyOptions opts = new Validator.VerifyOptions();
        opts.now = Instant.ofEpochSecond(now);
        opts.expectedIssuer = ISSUER;
        opts.expectedAudience = List.of(AUDIENCE);
        opts.issuerKeys = Map.of("ca-2026-01", p.issuer.getPublic());
        opts.principalJwks = Map.of("principal-1", p.principal.getPublic());
        opts.presenterKey = p.principal.getPublic();
        opts.nonceStore = NonceStore.newMemNonceStore();
        opts.requestContext = ctx(now, "10.1.2.3", 1);
        opts.requestCapability = capDatabase(50);
        opts.capabilityPlugins = Map.of("database", (req, c) -> {
            int rows = req.params.path("max_rows").asInt();
            if (rows > 200) {
                throw new AicException("max_rows exceeds budget");
            }
        });
        return opts;
    }

    private static Constraints.RequestContext ctx(long now, String ip, int concurrent) {
        Constraints.RequestContext c = new Constraints.RequestContext();
        c.now = Instant.ofEpochSecond(now);
        try {
            c.sourceIp = InetAddress.getByName(ip);
        } catch (Exception ex) {
            throw new RuntimeException(ex);
        }
        c.concurrentCount = concurrent;
        return c;
    }

    @Test
    void validTokenPermits() throws Exception {
        Pair p = build();
        Validator.VerifyOptions opts = fullOpts(p, IAT + 60);
        Validator.Decision d = Validator.validate(p.outerToken, opts);
        assertTrue(d.permit);
        assertEquals(AGENT_ID, d.actor);
        assertEquals(PRINCIPAL_ID, d.principal);
        assertEquals(1, d.capabilities.size());
        // second use of the same token is still verifiable (nonce recorded once on DA validate)
        Validator.validate(p.outerToken, fullOpts(p, IAT + 61));
    }

    @Test
    void expiredTokenRejected() throws Exception {
        Pair p = build();
        Validator.VerifyOptions opts = fullOpts(p, IAT + 7200);
        AicException ex = assertThrows(AicException.class, () -> Validator.validate(p.outerToken, opts));
        assertTrue(ex.getMessage().contains("expired"), ex.getMessage());
    }

    @Test
    void tamperedSignatureRejected() throws Exception {
        Pair p = build();
        String[] seg = p.outerToken.split("\\.", -1);
        String bad = seg[0] + "." + seg[1] + ".BADSIG";
        AicException ex = assertThrows(AicException.class, () -> Validator.validate(bad, fullOpts(p, IAT + 60)));
        assertTrue(ex.getMessage().contains("signature invalid"), ex.getMessage());
    }

    @Test
    void unknownIssuerKidRejected() throws Exception {
        Pair p = build();
        Validator.VerifyOptions opts = fullOpts(p, IAT + 60);
        opts.issuerKeys = Map.of("other-kid", p.issuer.getPublic());
        AicException ex = assertThrows(AicException.class, () -> Validator.validate(p.outerToken, opts));
        assertTrue(ex.getMessage().contains("unknown issuer kid"), ex.getMessage());
    }

    @Test
    void noneAlgorithmRejected() throws Exception {
        Pair p = build();
        Claims.Header h = new Claims.Header("none", Validator.TYP_OUTER, "ca-2026-01");
        String tok = Jws.signCompact(serialize(h),
                serialize(new Claims.OuterClaims()), "ES256", p.issuer.getPrivate());
        AicException ex = assertThrows(AicException.class, () -> Validator.validate(tok, fullOpts(p, IAT + 60)));
        assertTrue(ex.getMessage().contains("none"), ex.getMessage());
    }

    @Test
    void wrongAlgorithmRejected() throws Exception {
        Claims.Header h = new Claims.Header("HS256", Validator.TYP_OUTER, "ca-2026-01");
        assertThrows(AicException.class,
                () -> Jws.signCompact(serialize(h), "{}".getBytes(), "HS256", null));
    }

    @Test
    void duplicateKeysRejected() throws Exception {
        byte[] hb = "{\"alg\":\"ES256\",\"alg\":\"ES256\",\"typ\":\"aic+jwt\",\"kid\":\"k\"}".getBytes();
        assertTrue(JwtJson.hasDuplicateKeys(hb));
        // also exercises the walker on nested objects and arrays
        assertTrue(JwtJson.hasDuplicateKeys("{\"a\":{\"b\":1,\"b\":2}}".getBytes()));
        assertTrue(JwtJson.hasDuplicateKeys("{\"a\":[{\"c\":1,\"c\":2}]}".getBytes()));
        assertTrue(!JwtJson.hasDuplicateKeys("{\"a\":[{\"c\":1}],\"b\":{\"d\":2}}".getBytes()));
    }

    @Test
    void nonceReuseRejected() throws Exception {
        Pair p = build();
        Validator.VerifyOptions opts = fullOpts(p, IAT + 60);
        Validator.validate(p.outerToken, opts); // first use consumes the nonce
        AicException ex = assertThrows(AicException.class, () -> Validator.validate(p.outerToken, opts));
        assertTrue(ex.getMessage().contains("nonce"), ex.getMessage());
    }

    @Test
    void capabilityNotAllowedRejected() throws Exception {
        Pair p = build();
        Validator.VerifyOptions opts = fullOpts(p, IAT + 60);
        opts.requestCapability = new Claims.Capability("database", "query:DELETE");
        AicException ex = assertThrows(AicException.class, () -> Validator.validate(p.outerToken, opts));
        assertTrue(ex.getMessage().contains("step9"), ex.getMessage());
    }

    @Test
    void unknownSchemeFailClosed() throws Exception {
        Pair p = build();
        Validator.VerifyOptions opts = fullOpts(p, IAT + 60);
        // capability is allowed by aic.capabilities but no plugin is registered
        opts.requestCapability = capDatabase(50);
        opts.capabilityPlugins = Map.of();
        AicException ex = assertThrows(AicException.class, () -> Validator.validate(p.outerToken, opts));
        assertTrue(ex.getMessage().contains("fail-closed"), ex.getMessage());
    }

    @Test
    void constraintViolatedRejected() throws Exception {
        Pair p = build();
        Validator.VerifyOptions opts = fullOpts(p, IAT + 60);
        opts.requestContext = ctx(IAT + 60, "192.168.0.9", 1);
        opts.requestContext.now = Instant.ofEpochSecond(IAT + 60);
        AicException ex = assertThrows(AicException.class, () -> Validator.validate(p.outerToken, opts));
        assertTrue(ex.getMessage().contains("step7") || ex.getMessage().contains("allowed-cidr"), ex.getMessage());
    }

    @Test
    void presenterKeyMismatchRejected() throws Exception {
        Pair p = build();
        Validator.VerifyOptions opts = fullOpts(p, IAT + 60);
        opts.presenterKey = ec().getPublic();
        AicException ex = assertThrows(AicException.class, () -> Validator.validate(p.outerToken, opts));
        assertTrue(ex.getMessage().contains("cnf"), ex.getMessage());
    }

    @Test
    void audienceConfusionRejected() throws Exception {
        Pair p = build();
        Validator.VerifyOptions opts = fullOpts(p, IAT + 60);
        opts.expectedAudience = List.of("https://evil.example.com");
        AicException ex = assertThrows(AicException.class, () -> Validator.validate(p.outerToken, opts));
        assertTrue(ex.getMessage().contains("audience confusion"), ex.getMessage());
    }

    @Test
    void representativeRequiresDa() throws Exception {
        Pair p = build();
        Validator.VerifyOptions opts = fullOpts(p, IAT + 60);
        Claims.Header h = new Claims.Header("ES256", Validator.TYP_OUTER, "ca-2026-01");
        Claims.OuterClaims outer = new Claims.OuterClaims();
        outer.iss = ISSUER;
        outer.sub = AGENT_ID;
        outer.aud = new Claims.Audience(List.of(AUDIENCE));
        outer.iat = IAT;
        outer.exp = IAT + 3600;
        outer.jti = p.nonce;
        outer.cnf = new Claims.Cnf(p.jkt);
        outer.aic = new Claims.AicClaims(1,
                new Claims.Principal(REALM, PRINCIPAL_ID, p.keyHash, "sha-256"),
                Validator.MODE_REPRESENTATIVE, new ArrayList<>(List.of(capDatabase(100))));
        String tok = Jws.signCompact(serialize(h), serialize(outer), "ES256", p.issuer.getPrivate());
        AicException ex = assertThrows(AicException.class, () -> Validator.validate(tok, opts));
        assertTrue(ex.getMessage().contains("requires a DA JWT"), ex.getMessage());
    }

    @Test
    void representativeSubsetEnforced() throws Exception {
        Pair p = build();
        Validator.VerifyOptions opts = fullOpts(p, IAT + 60);
        Claims.PaClaims pa = new Claims.PaClaims();
        pa.ver = 1;
        pa.principal = new Claims.Principal(REALM, PRINCIPAL_ID, p.keyHash, "sha-256");
        Claims.Capability grant = new Claims.Capability("database", "query:SELECT",
                JwtJson.parse("{\"max_rows\":100}"));
        pa.grants = new ArrayList<>(List.of(grant));
        pa.delegationPolicy = new Claims.DelegationPolicy(1, Validator.ALLOWED_MODE_REPRESENTATIVE);
        opts.pa = pa;

        // rebuild an outer token in representative mode whose capabilities
        // exceed the grants (query:DELETE not in query:*) -> step6 denies
        Claims.Header h = new Claims.Header("ES256", Validator.TYP_OUTER, "ca-2026-01");
        Claims.OuterClaims outer = new Claims.OuterClaims();
        outer.iss = ISSUER;
        outer.sub = AGENT_ID;
        outer.aud = new Claims.Audience(List.of(AUDIENCE));
        outer.iat = IAT;
        outer.exp = IAT + 3600;
        outer.jti = p.nonce;
        outer.cnf = new Claims.Cnf(p.jkt);
        outer.aic = new Claims.AicClaims(1,
                new Claims.Principal(REALM, PRINCIPAL_ID, p.keyHash, "sha-256"),
                Validator.MODE_REPRESENTATIVE,
                new ArrayList<>(List.of(new Claims.Capability("database", "query:DELETE"))));
        // representative outer also carries a DA in this profile
        Claims.Header daHdr = new Claims.Header("ES256", Validator.TYP_DA, "principal-1");
        Claims.DaClaims da = new Claims.DaClaims();
        da.ver = 1;
        da.agentId = AGENT_ID;
        da.principal = new Claims.Principal(REALM, PRINCIPAL_ID, p.keyHash, "sha-256");
        da.reason = new Claims.Reason("DATA_ANALYSIS", "window");
        da.capabilities = new ArrayList<>(List.of(new Claims.Capability("database", "query:DELETE")));
        da.delegationMode = Validator.MODE_REPRESENTATIVE;
        da.requestedLifetime = 3600;
        da.ts = IAT;
        da.nonce = p.nonce;
        String daTok = Jws.signCompact(serialize(daHdr), serialize(da), "ES256", p.principal.getPrivate());
        outer.da = daTok;
        String tok = Jws.signCompact(serialize(h), serialize(outer), "ES256", p.issuer.getPrivate());
        AicException ex = assertThrows(AicException.class, () -> Validator.validate(tok, opts));
        assertTrue(ex.getMessage().contains("step6"), ex.getMessage());
    }

    @Test
    void goGeneratedOuterTokenParsesAndVerifies() throws Exception {
        String da = GoFixtures.DA_TOKEN;
        String outer = GoFixtures.OUTER_TOKEN;
        PublicKey principalPub = KeyHash.jwkToPublic(GoFixtures.parseJwk());

        // the OUTER and DA tokens were signed with the same key in the fixture
        Jws.verifyCompact(da, "ES256", principalPub);
        Jws.verifyCompact(outer, "ES256", principalPub);

        Claims.OuterClaims parsed = JwtJson.MAPPER.readValue(Jws.parseCompact(outer)[1], Claims.OuterClaims.class);
        assertEquals("agent:db-analyst-01", parsed.sub);
        assertEquals(ISSUER, parsed.iss);
        assertEquals(Validator.MODE_REPRESENTATIVE, parsed.aic.delegationMode);
        assertEquals("0ZcOCORZNYy-DWpqq30jZyHnXgk7dNsQo0c1V3iR4vY", parsed.cnf.jkt);
        Claims.DaClaims daParsed = JwtJson.MAPPER.readValue(Jws.parseCompact(da)[1], Claims.DaClaims.class);
        assertEquals("agent:db-analyst-01", daParsed.agentId);

        // full pipeline must still reject: the fixture's hash_alg binding and
        // nonce do not conform (placeholder SHA-256 of empty input)
        Validator.VerifyOptions opts = new Validator.VerifyOptions();
        opts.now = Instant.ofEpochSecond(IAT + 60);
        opts.issuerKeys = Map.of("ca-2026-01", principalPub);
        opts.principalJwks = Map.of("principal-zhangsan-2026", principalPub);
        opts.requestContext = ctx(IAT + 60, "10.1.2.3", 1);
        AicException ex = assertThrows(AicException.class, () -> Validator.validate(outer, opts));
        assertTrue(ex.getMessage().contains("key_hash mismatch") || ex.getMessage().contains("nonce")
                || ex.getMessage().contains("step4"), ex.getMessage());
    }

    static final class GoFixtures {
        static final String DA_TOKEN = "eyJhbGciOiJFUzI1NiIsInR5cCI6ImFpYytkYStqd3QiLCJraWQiOiJwcmluY2lwYWwtemhhbmdzYW4tMjAyNiJ9.eyJ2ZXIiOjEsImFnZW50X2lkIjoiYWdlbnQ6ZGItYW5hbHlzdC0wMSIsInByaW5jaXBhbCI6eyJyZWFsbSI6ImNvcnAuY29tIiwiaWQiOiJ6aGFuZ3NhbiIsImtleV9oYXNoIjoiZTNiMGM0NDI5OGZjMWMxNDlhZmJmNGM4OTk2ZmI5MjQyN2FlNDFlNDY0OWI5MzRjYTQ5NTk5MWI3ODUyYjg1NSIsImhhc2hfYWxnIjoic2hhLTI1NiJ9LCJyZWFzb24iOnsiY29kZSI6IkRBVEFfQU5BTFlTSVMiLCJkZXNjIjoiU2NoZWR1bGVkIHByb2R1Y3Rpb24gZGF0YSBhbmFseXNpcyB3aW5kb3cifSwiY2FwYWJpbGl0aWVzIjpbeyJzY2hlbWUiOiJkYXRhYmFzZSIsImlkIjoicXVlcnk6U0VMRUNUIiwicGFyYW1zIjp7Im1heF9yb3dzIjoxMDB9fV0sImRlbGVnYXRpb25fbW9kZSI6InJlcHJlc2VudGF0aXZlIiwiY29uc3RyYWludHMiOlt7InNjaGVtZSI6InZhcndvZi9jb25zdHJhaW50LXYxIiwiaWQiOiJhbGxvd2VkLWNpZHIiLCJwYXJhbXMiOlsiMTAuMC4wLjAvOCJdfV0sInJlcXVlc3RlZF9saWZldGltZSI6MzYwMCwidHMiOjE3NTU0OTk5MDAsIm5vbmNlIjoiYUJjRGVGZ0hpSmtMbU5vUHFSc1R1VndYeVowMTIzNDU2Nzg5YWJjZGVmIn0.RUqMf76xEbbenvXz-3UsxEmV2M5_WwsGfr-i9eeI0zeesoaiUi_zvgrLUs9MiSgffPd4WV3nlIZ7U1daEJtsTw";
        static final String OUTER_TOKEN = "eyJhbGciOiJFUzI1NiIsInR5cCI6ImFpYytqd3QiLCJraWQiOiJjYS0yMDI2LTAxIn0.eyJpc3MiOiJodHRwczovL2NhLmV4YW1wbGUuY29tL2FpYyIsInN1YiI6ImFnZW50OmRiLWFuYWx5c3QtMDEiLCJhdWQiOlsiaHR0cHM6Ly9ndy5leGFtcGxlLmNvbSJdLCJpYXQiOjE3NTU1MDAwMDAsImV4cCI6MTc1NTUwMzYwMCwianRpIjoiYUJjRGVGZ0hpSmtMbU5vUHFSc1R1VndYeVowMTIzNDU2Nzg5YWJjZGVmIiwiY25mIjp7ImprdCI6IjBaY09DT1JaTll5LURXcHFxMzBqWnlIblhnazdkTnNRbzBjMVYzaVI0dlkifSwiYWljIjp7InZlciI6MSwicHJpbmNpcGFsIjp7InJlYWxtIjoiY29ycC5jb20iLCJpZCI6InpoYW5nc2FuIiwia2V5X2hhc2giOiJlM2IwYzQ0Mjk4ZmMxYzE0OWFmYmY0Yzg5OTZmYjkyNDI3YWU0MWU0NjQ5YjkzNGNhNDk1OTkxYjc4NTJiODU1IiwiaGFzaF9hbGciOiJzaGEtMjU2In0sImRlbGVnYXRpb25fbW9kZSI6InJlcHJlc2VudGF0aXZlIiwiY2FwYWJpbGl0aWVzIjpbeyJzY2hlbWUiOiJkYXRhYmFzZSIsImlkIjoicXVlcnk6U0VMRUNUIiwicGFyYW1zIjp7Im1heF9yb3dzIjoxMDB9fV0sImNvbnN0cmFpbnRzIjpbeyJzY2hlbWUiOiJ2YXJ3b2YvY29uc3RyYWludC12MSIsImlkIjoiYWxsb3dlZC1jaWRyIiwicGFyYW1zIjpbIjEwLjAuMC4wLzgiXX1dLCJjaGFpbl9kZXB0aCI6MCwibWF4X2RlcHRoIjoxfSwiZGEiOiJleUpoYkdjaU9pSkZVekkxTmlJc0luUjVjQ0k2SW1GcFl5dGtZU3RxZDNRaUxDSnJhV1FpT2lKd2NtbHVZMmx3WVd3dGVtaGhibWR6WVc0dE1qQXlOaUo5LmV5SjJaWElpT2pFc0ltRm5aVzUwWDJsa0lqb2lZV2RsYm5RNlpHSXRZVzVoYkhsemRDMHdNU0lzSW5CeWFXNWphWEJoYkNJNmV5SnlaV0ZzYlNJNkltTnZjbkF1WTI5dElpd2lhV1FpT2lKNmFHRnVaM05oYmlJc0ltdGxlVjlvWVhOb0lqb2laVE5pTUdNME5ESTVPR1pqTVdNeE5EbGhabUptTkdNNE9UazJabUk1TWpReU4yRmxOREZsTkRZME9XSTVNelJqWVRRNU5UazVNV0kzT0RVeVlqZzFOU0lzSW1oaGMyaGZZV3huSWpvaWMyaGhMVEkxTmlKOUxDSnlaV0Z6YjI0aU9uc2lZMjlrWlNJNklrUkJWRUZmUVU1QlRGbFRTVk1pTENKa1pYTmpJam9pVTJOb1pXUjFiR1ZrSUhCeWIyUjFZM1JwYjI0Z1pHRjBZU0JoYm1Gc2VYTnBjeUIzYVc1a2IzY2lmU3dpWTJGd1lXSnBiR2wwYVdWeklqcGJleUp6WTJobGJXVWlPaUprWVhSaFltRnpaU0lzSW1sa0lqb2ljWFZsY25rNlUwVk1SVU5VSWl3aWNHRnlZVzF6SWpwN0ltMWhlRjl5YjNkeklqb3hNREI5ZlYwc0ltUmxiR1ZuWVhScGIyNWZiVzlrWlNJNkluSmxjSEpsYzJWdWRHRjBhWFpsSWl3aVkyOXVjM1J5WVdsdWRITWlPbHQ3SW5OamFHVnRaU0k2SW5aaGNuZHZaaTlqYjI1emRISmhhVzUwTFhZeElpd2lhV1FpT2lKaGJHeHZkMlZrTFdOcFpISWlMQ0p3WVhKaGJYTWlPbHNpTVRBdU1DNHdMakF2T0NKZGZWMHNJbkpsY1hWbGMzUmxaRjlzYVdabGRHbHRaU0k2TXpZd01Dd2lkSE1pT2pFM05UVTBPVGs1TURBc0ltNXZibU5sSWpvaVlVSmpSR1ZHWjBocFNtdE1iVTV2VUhGU2MxUjFWbmRZZVZvd01USXpORFUyTnpnNVlXSmpaR1ZtSW4wLlJVcU1mNzZ4RWJiZW52WHotM1VzeEVtVjJNNV9Xd3NHZnItaTllZUkwemVlc29haVVpX3p2Z3JMVXM5TWlTZ2ZmUGQ0V1YzbmxJWjdVMWRhRUp0c1R3In0.UJkZbpgpzWzuNW665TfaMGY70xo4BcEA-qvGuL78bvsWF6eL4z2jI_uDnYWwLIOTgWOxWF_vAjYJ66owYo7hOA";
        static final String PRINCIPAL_JWK_JSON = "{\"kty\":\"EC\",\"crv\":\"P-256\",\"x\":\"rN1es49KexLagupeD_zOIiz974abUS-HWkDLW6sxUu4\",\"y\":\"B0uChX3GHDsRiVTSaXujwS_Nu_SJ9HtaXRpUMF8EVX4\"}";

        static KeyHash.Jwk parseJwk() {
            return KeyHash.parseJwk(PRINCIPAL_JWK_JSON.getBytes());
        }
    }
}